name: Run tests

on:
  push:
    branches:
      - 'main'

  release:
    types: [ prereleased ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  test_service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2

      - name: Build
        working-directory: ./service
        run: go build -v

      - name: Run tests
        working-directory: ./service
        run: go test ./... -v -coverprofile="coverage.out"

      - name: Upload coverage to Codacy
        working-directory:  ./service
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report --force-coverage-parser go -r coverage.out

