name: Run tests

on:
  push:
    branches:
      - 'main'

  release:
    types: [ prereleased ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: ./service

jobs:

  test_service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2

      - name: Build
        run: go build -v

      - name: Run tests
        run: go test ./... -v -coverprofile="coverage.out"

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          # or
          # api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: coverage.out
          language: 'go'

#      - name: Upload coverage to Codacy
#        working-directory: ./service
#        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report --force-coverage-parser go -r coverage.out

